apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-prometheus-alertmanager
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: eu-west-1c-gp2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-prometheus-server
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: eu-west-1c-gp2