apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    chart: traefik
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 10.14.1
    helm:
      values: |
        ports:
          apigw:
            port: 9090
            expose: true
            exposedPort: 9090
            protocol: TCP
          consul:
            port: 8500
            expose: true
            exposedPort: 8500
            protocol: TCP

        service:
          enabled: true
          type: NodePort
          
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      selfHeal: false
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ingressroutetcp-apigw-svc
  namespace: traefik2
spec:
  entryPoints:
    - apigw
  routes:
  - match: HostSNI(`*`)
    services:
    - name: nginx
      namespace: pepa
      port: 9090