apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
#    chart: traefik
    repoURL: https://github.com/traefik/traefik-helm-chart
    targetRevision: 249c289
    helm:
      values: |
        ports:
          traefik:
            port: 9000
            expose: true
            exposedPort: 9000
            protocol: TCP        
          apigw:
            port: 9090
            expose: true
            exposedPort: 9090
            protocol: TCP
          consul:
            port: 9000
            expose: true
            exposedPort: 9000
            protocol: TCP
          consul:
            port: 8500
            expose: true
            exposedPort: 8500
            protocol: TCP

        providers:
          kubernetesCRD:
            enabled: true
            allowCrossNamespace: true

        service:
          enabled: true
          type: NodePort
          annotations: {
            # service.beta.kubernetes.io/aws-load-balancer-internal: "true",
            # service.beta.kubernetes.io/aws-load-balancer-type: "nlb",
            # service.beta.kubernetes.io/aws-load-balancer-name: "test03-eks-traefik-lb"
          }          
          
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      selfHeal: false