apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: traefik
spec:
  project: default
  source:
#    repoURL: https://helm.traefik.io/traefik
    repoURL: https://github.com/traefik/traefik-helm-chart.git
    chart: traefik
    targetRevision: 10.14.1
    helm:
      values: |
        service:
          enabled: true
          type: NodePort
          
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      selfHeal: false