
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: persistent-storages
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  source:
    path: storage/pvc/
    repoURL: https://github.com/JosefMuron/my-traefik-app.git
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true