
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-routes
  namespace: argocd  
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  source:
    path: traefik/ingressroutes/
    repoURL: https://github.com/JosefMuron/my-traefik-app.git
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: false