apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-2-6-1
  namespace: argocd
spec:
  project: default
  source:
    chart: traefik
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 10.14.2
    helm:
      values: |
        ingressRoute:
          dashboard:
            enabled: false
        ports:
          web:
            port: 8000
            # hostPort: 8000
            expose: true
            exposedPort: 80
            protocol: TCP        
          websecure:
            port: 8443
            # hostPort: 8443
            expose: true
            exposedPort: 443
            # The port protocol (TCP/UDP)
            protocol: TCP
            # nodePort: 32443
            # Set TLS at the entrypoint
            # https://doc.traefik.io/traefik/routing/entrypoints/#tls
            tls:
              enabled: false
              # this is the name of a TLSOption definition
              options: ""
              certResolver: ""
              domains: []
              # - main: example.com
              #   sans:
              #     - foo.example.com
              #     - bar.example.com        
          argocd:
            port: 8080
            expose: true
            exposedPort: 8080
            protocol: TCP         
          traefik:
            port: 9000
            expose: false
            exposedPort: 9000
            protocol: TCP        
          nginx:
            port: 9090
            expose: true
            exposedPort: 9090
            protocol: TCP
          metrics:
            port: 9100
            expose: true
            exposedPort: 9100
            protocol: TCP
          consul:
            port: 8500
            expose: false
            exposedPort: 8500
            protocol: TCP
          grafana:
            port: 8081
            expose: false
            exposedPort: 8081
            protocol: TCP
            nodePort: 32000

        metrics:
          prometheus:
            entryPoint: metrics
            buckets:
              - 0.1
              - 0.3
              - 1.2
              - 5.0
            addEntryPointsLabels: true
            addRoutersLabels: true
            addServicesLabels: true
            
        providers:
          kubernetesCRD:
            enabled: true
            allowCrossNamespace: true

        ingressClass:
          enabled: false
          isDefaultClass: false
          fallbackApiVersion: ""

        service:
          enabled: true
          type: LoadBalancer
          annotations: {
            service.beta.kubernetes.io/aws-load-balancer-internal: "false",
            service.beta.kubernetes.io/aws-load-balancer-type: "nlb",
            service.beta.kubernetes.io/load-balancer-source-ranges: "94.242.124.58/32, 34.117.59.81/32, 193.165.169.170/32, 90.181.164.130/32, 193.165.201.34/32",
            # service.beta.kubernetes.io/aws-load-balancer-type: "external",
            # service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance",
            # service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing",
            # service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*",
            service.beta.kubernetes.io/aws-load-balancer-name: "marta02-eks-traefik-lb"
          }
          # spec: {
          #   externalTrafficPolicy: Cluster
          # }
                      
        logs:
          general:
            level: DEBUG
          access:
            enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true