apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx # Name of the deployment
  namespace: nginx # Name of the namespace
  labels:
    app: nginx # Name of your application
spec:
  selector:
    matchLabels:
      app: nginx # Name of your application
  replicas: 1 # Number of replicas
  template:
    metadata:
      labels:
        app: nginx # Name of your application
    spec:
      containers:
      # Containers are the individual pieces of your application that you want
      # to run.
      - name: nginx # Name of the container
        image: nginx:latest # The image you want to run
        # resources:
        #   limits:
        #     memory: 512Mi
        #     cpu: "1"
        #   requests:
        #     memory: 256Mi
        #     cpu: "0.2"
        ports:
        # Ports are the ports that your application uses.
        - containerPort: 80 # The port that your application uses
      #   volumeMounts:
      #   # VolumeMounts are the volumes that your application uses.
      #   - mountPath: /var/www/html # The path that your application uses
      #     name: vol0 # Name of the volume
      # volumes:
      # # Volumes are the persistent storage that your application uses.
      # - name: vol0 # Name of the volume
      #   persistentVolumeClaim:
      #     claimName: pvc0 # Name of the persistent volume claim
---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx
spec:
  selector:
    app: nginx
  type: ClusterIP
  ports:
  - name:  http
    port:  9090
    targetPort: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ingressroutetcp-nginx-svc
  namespace: nginx
spec:
  entryPoints:
    - web
  routes:
  - match: HostSNI(`*`)
    middlewares:
    - name: middlewaretcp-ipwhitelist-nginx
      namespace: nginx
    services:
    - name: nginx
      namespace: nginx
      port: 9090
---
apiVersion: traefik.containo.us/v1alpha1
kind: MiddlewareTCP
metadata:
  name: middlewaretcp-ipwhitelist-nginx
  namespace: nginx
spec:
  ipWhiteList:
    sourceRange:
      # - 193.165.201.34
      # - 127.0.0.1/32
      # - 94.242.124.58
      # - 54.155.204.184
      # - 34.250.192.16
      # - 52.19.166.176
      - 10.29.0.0/16