apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: route-grafana
  namespace: traefik
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: "Host(Path(`/grafana`))"
    middlewares:
      - name: grafana-middleware-stripprefix
    services:
    - name: grafana
      namespace: monitoring
      port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: grafana-middleware-stripprefix
  namespace: traefik
spec:
  stripPrefix:
    prefixes:
      - /grafana