apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: route-grafana
  namespace: traefik
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: "Host(`pepa-test04.zonkej.cz`) && (PathPrefix(`/grafana`)"
    middlewares:
      - name: grafana-chain
    services:
    - name: grafana
      namespace: monitoring
      port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: grafana-chain
spec:
  chain:
    middlewares:
    - name: grafana-replacepath
    - name: grafana-middleware-stripprefix
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: grafana-middleware-stripprefix
  namespace: traefik
spec:
  stripPrefix:
    prefixes:
      - /grafana
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: grafana-replacepath
spec:
  replacePath:
    path: /grafana