apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: route-grafana
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: "Host(`pepa-test04.zonkej.cz`) && (PathPrefix(`/grafana`))"
    middlewares:
      - name: grafana-middleware-stripprefix
    services:
    - name: grafana
      namespace: monitoring
      port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: grafana-middleware-stripprefix
  namespace: monitoring
spec:
  stripPrefix:
    prefixes:
#      - "/grafana/[a-z0-9]+/[0-9]+/"
      - /grafana        