apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: routetcp-nginx-svc
  namespace: traefik
spec:
  entryPoints:
    - nginx
  routes:
  - match: HostSNI(`*`)
    # middlewares:
    # - name: middlewaretcp-ipwhitelist-nginx
    #   namespace: nginx
    services:
    - name: nginx
      namespace: nginx
      port: 9090
---
apiVersion: traefik.containo.us/v1alpha1
kind: MiddlewareTCP
metadata:
  name: middlewaretcp-ipwhitelist-nginx
  namespace: traefik
spec:
  ipWhiteList:
    sourceRange:
      # - 193.165.201.34
      - 127.0.0.1/32
      - 10.29.0.0/16