apiVersion: v1
kind: Secret
metadata:
  name: zonkej-secret
type: kubernetes.io/tls
data:
  # the data is abbreviated in this example
  tls.crt: |
        MIIFYDCCBEigAwIBAgIQQAF3ITfU6UK47naqPGQKtzANBgkqhkiG9w0BAQsFADA/
MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
DkRTVCBSb290IENBIFgzMB4XDTIxMDEyMDE5MTQwM1oXDTI0MDkzMDE4MTQwM1ow
TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwggIiMA0GCSqGSIb3DQEB
AQUAA4ICDwAwggIKAoICAQCt6CRz9BQ385ueK1coHIe+3LffOJCMbjzmV6B493XC
ov71am72AE8o295ohmxEk7axY/0UEmu/H9LqMZshftEzPLpI9d1537O4/xLxIZpL
wYqGcWlKZmZsj348cL+tKSIG8+TA5oCu4kuPt5l+lAOf00eXfJlII1PoOK5PCm+D
LtFJV4yAdLbaL9A4jXsDcCEbdfIwPPqPrt3aY6vrFk/CjhFLfs8L6P+1dy70sntK
4EwSJQxwjQMpoOFTJOwT2e4ZvxCzSow/iaNhUd6shweU9GNx7C7ib1uYgeGJXDR5
bHbvO5BieebbpJovJsXQEOEO3tkQjhb7t/eo98flAgeYjzYIlefiN5YNNnWe+w5y
sR2bvAP5SQXYgd0FtCrWQemsAXaVCg/Y39W9Eh81LygXbNKYwagJZHduRze6zqxZ
Xmidf3LWicUGQSk+WT7dJvUkyRGnWqNMQB9GoZm1pzpRboY7nn1ypxIFeFntPlF4
FQsDj43QLwWyPntKHEtzBRL8xurgUBN8Q5N0s8p0544fAQjQMNRbcTa0B7rBMDBc
SLeCO5imfWCKoqMpgsy6vYMEG6KDA0Gh1gXxG8K28Kh8hjtGqEgqiNx2mna/H2ql
PRmP6zjzZN7IKw0KKP/32+IVQtQi0Cdd4Xn+GOdwiK1O5tmLOsbdJ1Fu/7xk9TND
TwIDAQABo4IBRjCCAUIwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYw
SwYIKwYBBQUHAQEEPzA9MDsGCCsGAQUFBzAChi9odHRwOi8vYXBwcy5pZGVudHJ1
c3QuY29tL3Jvb3RzL2RzdHJvb3RjYXgzLnA3YzAfBgNVHSMEGDAWgBTEp7Gkeyxx
+tvhS5B1/8QVYIWJEDBUBgNVHSAETTBLMAgGBmeBDAECATA/BgsrBgEEAYLfEwEB
ATAwMC4GCCsGAQUFBwIBFiJodHRwOi8vY3BzLnJvb3QteDEubGV0c2VuY3J5cHQu
b3JnMDwGA1UdHwQ1MDMwMaAvoC2GK2h0dHA6Ly9jcmwuaWRlbnRydXN0LmNvbS9E
U1RST09UQ0FYM0NSTC5jcmwwHQYDVR0OBBYEFHm0WeZ7tuXkAXOACIjIGlj26Ztu
MA0GCSqGSIb3DQEBCwUAA4IBAQAKcwBslm7/DlLQrt2M51oGrS+o44+/yQoDFVDC
5WxCu2+b9LRPwkSICHXM6webFGJueN7sJ7o5XPWioW5WlHAQU7G75K/QosMrAdSW
9MUgNTP52GE24HGNtLi1qoJFlcDyqSMo59ahy2cI2qBDLKobkx/J3vWraV0T9VuG
WCLKTVXkcGdtwlfFRjlBz4pYg1htmf5X6DYO8A4jqv2Il9DjXA6USbW1FzXSLr9O
he8Y4IWS6wY7bCkjCWDcRQJMEhg76fsO3txE+FiYruq9RUWhiF1myv4Q6W+CyBFC
Dfvp7OOGAN6dEOM4+qR9sdjoSYKEBpsr6GtPAQw4dy753ec5
  tls.key: |
        MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC5F2x1NqT8F2x9
f+j8+8WoMKXwsHMFRpfbpgyza7MBmZzZf5ryn4q2igsnOlofrh3NWCfmvlHNT3fF
8pMtXyQ7lQ94uHGTA0/3RJVePnn1Mb6s2CqwKC/xUfyU/k51bh9aV20FeY2Yez+m
MjWPEFTbwm+oOzDFaUc/6BjdUq45Y8GtyG0U40N5cScUjzq8VdpTKoExYmL/xJMW
Zjw0BvPw6dHEgOB3TCbqA0tVFT7cE3tE1WvWwWVHLlvS1QmCkCAd2Zxg9b/ivWOU
NrIn3exr1JGUgDDBUCnuvXmVwbPchZihv1Xgw0/53dGW3FUTWa2O7sf2U46bMFFn
CL9hJA+hAgMBAAECggEAZ5h1qvFHzJUrst6JwDcG/UklR57q8dP+IQFCcJXiHg4l
XRLv3cZwNBT1gyJE2SByK8Ggq6RwUpKc/hz0RVvQAs0+WJobb2ZWNpabZ6FeT19l
Uoa29du4YcA6uAXSUiWtxLnUGlFbcDHjgRjvI0DHzix4pFdkx8lSCLHWYOHrA9Ef
IUxvgZaDvgc7X5g/MiSfRhwHt2tGTk2/zXTjZIm9oWp2my/IpR4GSVnwMZc86QtK
AEUw924KjapQEYtnQbYnWLgj932KjTJFGuxybbK4wZjSgyfHWbjECWfLh3dL/obj
0FIKLXZNnBS1c2uM7lOwnAd7xJXv8Awjv+NFPifBAQKBgQDcKZ69NNQ/opOcEDf0
QfmrHPWd9fj1kNi6XpKtGGgfbmgE8RKiMxGAPx7T2bRah0vvY8PSYTm6T/Lh06uv
q6Dvk+w+OEzppriUfY8FJw66odJtRMP1k8chxnaObXR+3ergi4C+6Nmcp0Uognfz
8+HiQf8gzxBN7Y8nK2IWumGF0QKBgQDXOFvnJkLcQAiSw9QwQsQUSAPeIlthZ37B
cscGjxwG3qwX3hXBq2V1PS/CpJ80aEOCOSL0bV1G5s+8Nx+hZTidv5ti+hr+WFkg
0buMvqrfRB/bqMeKbc4Ohy4Lqgl/6MneEM1ESmU5D21mfcMshbpsiI7QAGJeZvyV
4qHwpQzQ0QKBgAWrrMMC0VSyQ0sJv+cyq9OUc18WLstkZ7ClLvH2ZvgoR9WYv/od
hp3fAlRCjzqlsXcBAtIwXuRFmuPmJ83mhcal8LfJi3GZMbfhZAWl8+Mqt9jIpKN2
ovJjwjn45788yAfwj+ha5v/57vYUJjLKXU8OlBusOadILx+7JlOfiVOBAoGBAKRG
uJ+vbMmBdwnPwF82F0UD0y/zOZ0XyoEOgyxWgCYeQW3WbvTtRvw+P/5qebse+qij
xDKeZ9x+wYIA8XvYL2b5ojnifkg2V5HdhTLhNrxE26xnIChhuC8Or+7nU2j2319J
o+TEhI8RX4gj5p5NVQcTFS9fm7ZDFfmyi7mLwkSBAoGBAJl6wuDV2qduGjvOCh79
e7s39dxRhYBl3hH72+lB5mOZSDvtV6ehjKu0ZT8+F3Ll19KxDtTMFZ0hfWCi9oFk
eGSXuao/rWhJVd75oR+lJ3O8oaS3gcg+1dEx8rK6nBLPVeqTsHgKEIx6HYMc/HVZ
vP44BOEvzuqtGYWA8h4itRQA
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: default
spec:
  defaultCertificate:
    secretName: zonkej-secret